### ISSUE TITLE
Python 3 OOP Part 4 - Polymorphism / Unforgiveness

### ISSUE THREAD

**Issue by skyjur** [TheDigitalCatOnline/thedigitalcatonline.github.com#1]
Hi! I was looking for some material for python beginners and came across your articles and I think they are great.

I would like to comment on _## Unforgiviness_ part in http://blog.thedigitalcatonline.com/blog/2014/08/21/python-3-oop-part-4-polymorphism/#.V-EUsR8zrCI

I am a little bit confused as to why this is not good:

```
if hasattr(someobj, 'open'):
    [...]
else:
    [...]
```

and this is "better":

```
try:
    someobj.open()
    [...]
except AttributeError:
    [...]
```

in my experience second is prone to catching unintended AttributeError:

```
try:
    someobj.open()   <-- AttributeError can happen deeper in the open() stack, very common!
    [...]   <-- AttributeError might also happen here
except AttributeError:
    [...]
```

In my experience this happens really often and errors that otherwise would had been very easy to pinpoint the cause become very hard to debug.

I understand that 'hasattr' might have issues if attribute is implemented through `def __getattr__`. I think better solution that doesn't have same issue as `hasattr` and is not more verbose that try/except block is:

```
    open_func = getattr(obj, 'open', None)
    if open_func:
         open_func()
```

Using try/except with AttributeError, I think the only good way is if try blocck doesn't have anything else in it, for example like this:

```
    try:
        something = obj.something
    except AttributeError:
        ...
```

But I don't find any good reason to prefer this instead of  `getattr(...)`.

Maybe better example to illustrate "better ask for forgiveness" could be like this:

```
   if obj.can_open():
       obj.open()
   else:
      ...
```

vs

```
   try:
      obj.open()
   except CantOpenDoors:
      ....
```

I think this would better illustrate the intended idea behind "better ask for forgiveness" when it comes to implementation of interfaces. It's easier to implement `def open()` and throw a helpful error if cant open, instead of having to implement `def can_open()`.

**Comment by lgiordani** [comment]
Thank you for your comment, I will review it as soon as possible. Thanks for the contribution!

**Comment by lgiordani** [comment]
I cannot believe I left this without answer for 2 years :see_no_evil: 
I am very sorry. I believe the issue you point out is real and not trivial. The try/except blocks should be very targeted and localised, and this assumes that errors are correctly caught deeper. As you point out you shouldn't have too much code in the try block or you risk to catch and exception raised later there, which however is not incorrect. The problem of the `obj.can_open()` is obviously that it forces you to implement a method that checks if you can do something, but this is not polymorphic at all, as it requires the object to provide a "check" for something, and we quickly lose the inversion of dependency.
I guess after 2 years the answer might be useless, sorry. :see_no_evil: 
Feel free to submit another issue, this time I promise I will be more responsive
