### ISSUE TITLE
OOP concepts in Python 2.x - Part 1

### ISSUE THREAD

**Issue by helfgott** [TheDigitalCatOnline/thedigitalcatonline.github.com#10]
**From:** http://blog.thedigitalcatonline.com/blog/2014/03/05/oop-concepts-in-python-2-dot-x-part-1/

> The Python syntax to instantiate a class is the same of a function call

Shouldn't it be this:

> The Python syntax to instantiate a class is the same of a variable assignment

By reading your article the concept of instance I get is when you have an specific object created a "concrete object" which is the instance of the class, in your code example:

```
>>> b = int()
>>> type(b)
<type 'int'> 
```

When you create the instance of int() as "b" 

Or you describe it like that because, only at the moment of the execution of `type(b)` is when the instance is actually created? This seems quite probable but I want to be sure about it.

In stackoverflow I saw this definition of instance:

> Instance is a variable that holds the memory address of the Object.

In that case the correction I propose would be valid.

I've also created a question on S.O because I'm quite curious about the concept:

https://stackoverflow.com/questions/54260482/when-should-i-call-it-instance

**Comment by helfgott** [comment]
By the answers given on S.O I found that actually the instances are created or exist at the moment of execution, so your description is quite wel..

**Comment by lgiordani** [comment]
@helfgott sorry for not answering before, it was in my TODO list. Glad to know that it has been clarified elsewhere, I will read the SO thread to see if something can be explained in a better way. Thanks!
