### ISSUE TITLE
Improvement in Python mocks - A gentle introduction - Part 1

### ISSUE THREAD

**Issue by schneeemensch** [TheDigitalCatOnline/thedigitalcatonline.github.com#12]
Hey,

I have been enjoying the articles on your blog and found some minor improvements in the article about python mocks:

In the code examples explaining the side_effect attribute you call side_effect directly instead of calling the mock_object which throws the side_effect.

Your example:
```
 >>> def print_answer():
...     print("42")       
>>> m.some_attribute.side_effect = print_answer
>>> m.some_attribute.side_effect()
42
```

Example which actually shows the advantage of using a side_effect:
```
 >>> def print_answer():
...     print("42")       
>>> m.some_attribute.side_effect = print_answer
>>> m.some_attribute()
42
```

you have done it correctly in the first example using range(3), but switched to calling side_effect for the later examples.

I hope you can fix this minor issue.
Thanks for your work,
schneeemensch

**Comment by lgiordani** [comment]
Oh, you are so right. I'm going to fix it asap. This is the "close issues and PRs" week :wink: Thanks for submitting it!

**Comment by lgiordani** [comment]
Fixed! Thanks
