### ISSUE TITLE
site hard to read for people with poor vision

### ISSUE THREAD

**Issue by jeffsilverm** [TheDigitalCatOnline/thedigitalcatonline.github.com#14]
Please make the text color dark blue, dark purple, or black.  Hard to read gray text on a white background.
Also, google+ was deprecated by google.

Thank you.

**Comment by lgiordani** [comment]
Hi! Sorry for the late reply. Thanks for mentioning this, I'm not that into web development, so I tend to forget to check things like contrast and colour associations. Will fix this as soon as possible

**Comment by jeffsilverm** [comment]
Thank you.  Better late than never.

Jeff



--
Jeff Silverman, Linux sysadmin
to five three for phive niner too tree won ate
jeffsilverm 4t gmail.c0m
http://www.commercialventvac.com
See my portfolio of writings and talks
<http://www.commercialventvac.com/portfolio.html>

**Comment by lgiordani** [comment]
Hi! I just updated the site with a nice darker text colour. I really hope this helps. If not, just reopen this and we can discuss it further. Thanks for flagging this.
