### ISSUE TITLE
I am observing small issue with tail recursion version of flattening!

### ISSUE THREAD

**Issue by mighty-raj** [TheDigitalCatOnline/thedigitalcatonline.github.com#15]
Hi, i see tail recursion version needs some correction with 3rd case case stmnt!, becoz, i see you are not handling a scenario of nested lists  inside a input list, if nested list is not at the end of the input list!

url @ https://www.thedigitalcatonline.com/blog/2015/04/07/99-scala-problems-07-flatten/ 

Example case:  List(List(1,2), 3, List(4, List(5,6)), List(7, List(8,9)))
As you can see above, this example has 2 nested lists at the end, this scenario is not handled, i feel... becoz when i tested your solution did not flattened the last but one!

Below is what i tried:

```
def flattenTailRec[A](l : List[A]): List[A] = {
    def _flattenTailRec(res: List[A], rem: List[A]): List[A] = rem match {
      case Nil => res
      case (h:List[A])::tail => _flattenTailRec(_flattenTailRec(res, h), tail)
      case (h:A)::tail => _flattenTailRec( res ::: List(h), tail)
    }
    _flattenTailRec(List[A](), l)
  }
```

I might be wrong also, correct me if i missed anything here! 

BTW, your solutions are very helpful... Cheers :)

**Comment by lgiordani** [comment]
Oh, thank you I'll have a closer look as soon as possible. It is completely possible my solution is partially wrong, after all I was learning Scala at the time. Thanks! Will come back to you soon

**Comment by mighty-raj** [comment]
sure, let me know once you check, thank you !

**Comment by lgiordani** [comment]
Hi! I fixed the code on the blog. You are very right, I was missing a call of `flatten` in one of the cases. I also added to the blog that I need to learn TDD in Scala, such cases would be so easy to spot! Thanks a lot for your contribution
