### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by tomasz-rozanski** [TheDigitalCatOnline/thedigitalcatonline.github.com#17]
In the [Exploring the Amiga - Part 3](https://www.thedigitalcatonline.com/blog/2018/06/08/exploring-the-amiga-3/) article, the phrase:

> (...) the ***note*** type for a library (...)

should read
>  (...) the ***node*** type for a library (...)

**Comment by lgiordani** [comment]
Thanks @tomasz-rozanski I fixed it now.
