### ISSUE TITLE
Broken code example in Mixin-classes page

### ISSUE THREAD

**Issue by TimChild** [TheDigitalCatOnline/thedigitalcatonline.github.com#18]
In this page - [mixing-classes...](https://www.thedigitalcatonline.com/blog/2020/03/27/mixin-classes-in-python/) there is a code example (see below) which as far as I can tell is broken. 
I'm not sure how to fix it as I was reading your article to try learn how Mixin's work, but I'm pretty sure this code is not behaving as you describe below. When running this myself, the `LimitSizeMixin` is completely skipped. 
Apologies in advance if this is in fact my mistake as I am quite new to Python. 

Tim

```python
class GraphicalEntity:
    def __init__(self, pos_x, pos_y, size_x, size_y):
        self.pos_x = pos_x
        self.pos_y = pos_y
        self.size_x = size_x
        self.size_y = size_y


class Button(GraphicalEntity):
    def __init__(self, pos_x, pos_y, size_x, size_y):
        super().__init__(pos_x, pos_y, size_x, size_y)
        self.status = False

    def toggle(self):
        self.status = not self.status


class LimitSizeMixin:
    def __init__(self, size_x, size_y, size):
        size_x = min(size_x, 500)
        size_y = min(size_y, 400)
        super().__init__(pos_x, pos_y, size_x, size_y)


class LimitSizeButton(Button, LimitSizeMixin):
    pass

b = LimitSizeButton(10, 20, 200, 100)
```

> Here, LimitSizeButton calls __init__ of its first parent, which is Button. This, however, delegates the call to the next class in the MRO before initialising self.status, so the call is dispatched to LimitSizeMixin, that first operates some changes and eventually dispatches it to the original recipient, GraphicalEntity.
> 
> Remember that in Python, you are never forced to call the parent's implementation of a method, so the mixin here might also stop the dispatching mechanism if that is the requirement of the business logic of the new object.

**Comment by TimChild** [comment]
I think this may be what is intended? 

```python
class GraphicalEntity:
    def __init__(self, pos_x, pos_y, size_x, size_y):
        self.pos_x = pos_x
        self.pos_y = pos_y
        self.size_x = size_x
        self.size_y = size_y


class Button(GraphicalEntity):
    def __init__(self, pos_x, pos_y, size_x, size_y):
        super().__init__(pos_x, pos_y, size_x, size_y)
        self.status = False

    def toggle(self):
        self.status = not self.status


class LimitSizeMixin:
    def __init__(self, pos_x, pos_y, size_x, size_y):
        size_x = min(size_x, 500)
        size_y = min(size_y, 400)
        super().__init__(pos_x, pos_y, size_x, size_y)


class LimitSizeButton(LimitSizeMixin, Button):
    pass

b = LimitSizeButton(10, 20, 200, 100)
```

**Comment by lgiordani** [comment]
Hey @TimChild thanks a lot for this. I quickly reviewed the code and it's all over the place, I don't know what I was thinking. Give me a couple of days, I want to read the post again and check the flow of the explanation to see if/where I messed up in other places. Will update shortly. Thanks again!

**Comment by lgiordani** [comment]
Hey @TimChild apologies for taking so long to fix it. Yeah, the code that you suggested is the correct one, I fixed the post there and also explained a couple of passages more in detail. I just pushed the changes to the website. Thanks a lot for reporting this!
