### ISSUE TITLE
im trying to print last element of list, but the below code snippet does not giving any ouptut. can you please explai why it is not giving

### ISSUE THREAD

**Issue by Akhileshcloud7** [TheDigitalCatOnline/thedigitalcatonline.github.com#19]
import java.util.NoSuchElementException

object P01 extends App {

    val le= List("sadj","aksjd","laksd","oido")
    def LastEle[A](le:List[A]):A= le.last

   val lrecr=List(1,5,3,23,45)
   def lastRecur[A](ls:List[A]) :A = ls match {

    case h::Nil => h
    case _::tail => (lastRecur(tail))
    case _ => throw new NoSuchElementException
 }

}

**Comment by lgiordani** [comment]
Sorry where does that code come from? I'm not sure what you are referring to

**Comment by Akhileshcloud7** [comment]
Hi @lgiordani

Thanks for response and please find the below code snippet to print last element of List,


object P01 extends App {
    val le= List("sadj","aksjd","laksd","oido")

         def LastEle[A](le:List[A]):A= le.last

        val lrecr=List(1,5,3,23,45)
      def lastRecur[A](ls:List[A]) :A = ls match {
               case h::Nil => h
               case _::tail => (lastRecur(tail))
               case _ => throw new NoSuchElementException

  }

can you pleas correct my code to get output.

**Comment by lgiordani** [comment]
OK, I see you are referring to "99 Scala Problems 01 - Find the last element of a list".

Well, I don't see any problem in your code. This is the recording of my session in the Scala REPL

``` text
Welcome to Scala 2.11.12 (OpenJDK 64-Bit Server VM, Java 1.8.0_252).
Type in expressions for evaluation. Or try :help.

scala> val lrecr=List(1,5,3,23,45)
lrecr: List[Int] = List(1, 5, 3, 23, 45)

scala> def lastRecur[A](ls:List[A]) :A = ls match {
     |     case h::Nil => h
     |     case _::tail => (lastRecur(tail))
     |     case _ => throw new NoSuchElementException
     | }
lastRecur: [A](ls: List[A])A

scala> lastRecur(lrecr)
res0: Int = 45

scala>
```

As you can see your function works. If I misunderstood your problem, please tell me.

For the future, however, please follow this suggestions:
1. When you send an issue to a project or to a blog use a simple title. In this example it could have been "Scala: find the last element in a list".
2. In the description of the issue show your code and show evidence of what is not working. In particular, take your time to properly format the code (the above snippet is not complete and not properly formatted) using the GitHub Flavoured Markdown.

Providing your code in a GItHub repository (or any other online repository manager) or online playgrounds like https://scalafiddle.io/ for Scala greatly helps to work together on some code.

Remember that whoever receives the issue does not know what you are working on, so the more information you give the better. In this case I couldn't even understand which post/language you were referring to, for example. And still do not know what error you have.

Hope this helps!

**Comment by Akhileshcloud7** [comment]
I'm trying to print last but one element of the list, this is the code snippet here. But when I ran this code, code is not giving any output on console though the program executes successfully, and when I tried to put println() statement its throwing error with return type of function. Please find the below output and help to get the output of code


`object P02 extends App {

     //Find the last but one element of a list.
     val l=List(4,5,3,9,1)
    def penultimatEele[A](l:List[A]):A = {

      if (l.isEmpty) throw new NoSuchElementException
      l.init.last

    }

  def penult[A](n:Int, l:List[A]):A={

    if (n<=0) throw new IllegalArgumentException
    if (n>l.length) throw new NoSuchElementException
    l.takeRight(n).head
  }
}`

**Comment by Akhileshcloud7** [comment]
thanks @lgiordani for the answer and I'll follow your instructions,
