### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by kentavr009** [TheDigitalCatOnline/thedigitalcatonline.github.com#24]
Hi there,

How can we talk? All form that are presented on your site do not work!

**Comment by lgiordani** [comment]
Hi, which forms on the site? Feel free to post questions here, anyway.

**Comment by kentavr009** [comment]
Hello once again, I am an employee of the captcha solve service. I loved your blog, and I would like to discuss the possibility of publishing a guest post on your blog or a useful article in which our service will be mentioned. Is it possible?
