### ISSUE TITLE
Add console output to blog post

### ISSUE THREAD

**Issue by TimoMorris** [TheDigitalCatOnline/thedigitalcatonline.github.com#25]
Just read your recent [blog post on composition and inheritance](https://www.thedigitalcatonline.com/blog/2020/08/17/delegation-composition-and-inheritance-in-object-oriented-programming/), which I found really helpful - I particularly appreciated the framing around "collaboration of entities".

This isn't a correction per se, but thought I'd mention by way of feedback that it would have been really useful to have the console output from the examples, e.g. when calling the `.info()` methods. It would really help with being able to follow how the inheritance/composition is working. I appreciate the system you use for publishing your posts might not support console output e.g. in the same way as the official Python docs has, but even having them as single-line comments below the method calls/print statements would suffice.

Thanks again for the great article! 😊

**Comment by lgiordani** [comment]
Hey @TimoMorris thanks for reading it and for the suggestion, it sounds very reasonable. I will add the output as soon as possible. Thanks again!

**Comment by lgiordani** [comment]
@TimoMorris not very promptly, but I fixed this :sweat_smile: Thanks!
