### ISSUE TITLE
Flask project setup: TDD, Docker, Postgres and more - Part 2

### ISSUE THREAD

**Issue by RenzoDlcU** [TheDigitalCatOnline/thedigitalcatonline.github.com#26]
Hello, I have this problem in the part 2 in step 5 of this guide, can you help me?
![image](https://user-images.githubusercontent.com/56940932/95705101-7c5ab580-0c18-11eb-82f3-6237881f7d5a.png)

**Comment by lgiordani** [comment]
Hi! I'm amending the posts as I found a couple of errors, but in the meanwhile I'll answer this particular one here. You need to create the empty file `tests/__init__.py` to make pytest correctly load the code. Sorry, I failed to mention it! Let me know if it works

**Comment by RenzoDlcU** [comment]
Yeah! That's worked for me, but I have one question more, why I have to run the script 2 times, the first time print a error and the second time run successful? I put a screenshot. Anyway, thank you very much for your help, you are incredible! 
![image](https://user-images.githubusercontent.com/56940932/96217629-a11c9900-0f48-11eb-9e1b-3644d199781b.png)

**Comment by lgiordani** [comment]
Oh, that's bad. This happens because (I think) the docker container takes time to become available. I saw this error before, but honestly at the moment I don't remember how I solved it. I will investigate. In the meanwhile, if you want to dig into this, you can have a look at how the docker-compose system decides a container is up and running. I might be mistaken, this is just a hunch

**Comment by lgiordani** [comment]
I just pushed an updated version of the posts, fixing some mistakes and typos. I also updated some code snippets and added the links to a companion repository with the full source code and the changes step by step. Can you please check that everything is in sync before we try to debug that error that you have? The `manage.py` contains a protection against that condition, so I suspect you might have missed something. Let me know!

**Comment by lgiordani** [comment]
@RenzoDlcU Any luck with the new version of the posts?
