### ISSUE TITLE
Typos in TDD in Python with pytest

### ISSUE THREAD

**Issue by 4myhw** [TheDigitalCatOnline/thedigitalcatonline.github.com#27]
TDD in Python with pytest - Part 1. 
You use both py.test and pytest. They both gave me the same results but I am guessing you only intended to use one.
TDD in Python with pytest - Part 2
I believe "was easy" was contracted to wasy.

Thank you I am looking forward to the rest of the blog posts and I have already downloaded the book.

George

**Comment by lgiordani** [comment]
Thank you, I fixed both typos. `py.test` is the old name of that executable, and it still comes automatically out of my fingers :joy_cat:  And thanks for reading the book!
