### ISSUE TITLE
Code in TDD in Python with pytest - Part 5

### ISSUE THREAD

**Issue by 4myhw** [TheDigitalCatOnline/thedigitalcatonline.github.com#28]
In the blog post you have:
class FileInfo:
    [...]

    def get_info(self):
        return (
            self.filename,
            self.original_path,
            os.path.abspath(self.filename),
            os.path.getsize(self.filename)
        )

On github you have:

```
class FileInfo:
[...]

    def get_info(self):
        return (
            self.filename,
            self.original_path,
            os.path.abspath(self.original_path),
            os.path.getsize(self.original_path)
        )
```

**Comment by lgiordani** [comment]
Oh snap! Thanks, I'll fix it

**Comment by lgiordani** [comment]
Thank you, I fixed it now
