### ISSUE TITLE
Step 9.8 - Empty list before applying the thresholds

### ISSUE THREAD

**Issue by elyock** [TheDigitalCatOnline/thedigitalcatonline.github.com#32]
Test function is "test_avg_manages_empty_list_after_outlier_removal", identical to the step 9.7 test function--copy and paste error? ... Should probably be something like ...

def test_avg_manages_empty_list_before_outlier_removal():
    calculator = SimpleCalculator()
    result = calculator.avg([], lt=15, ut=90)
    assert result == 0

**Comment by lgiordani** [comment]
Thank you for spotting it, it was indeed a wrong copy and paste from the source code. It's fixed now
