### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by guntbert** [TheDigitalCatOnline/thedigitalcatonline.github.com#35]
https://github.com/TheDigitalCatOnline/thedigitalcatonline.github.com/blob/6f0ff4c3356f8481ff755cfc3fce2bc176cb6506/blog/2015/05/13/python-oop-tdd-example-part1/index.html#L714
The server of Jeff knupp doesn't seem to exist any more

**Comment by lgiordani** [comment]
Thanks. The URL jeffknupp.com is still listed in Jeff's Twitter profile, I wonder if this is a temporary error. I will notify him and act accordingly. Thanks for spotting it!

**Comment by lgiordani** [comment]
I removed the link as part as a rewrite of those posts. Thanks!
