### ISSUE TITLE
Mistake in header "Using mixins to hijack inheritance"

### ISSUE THREAD

**Issue by akocur** [TheDigitalCatOnline/thedigitalcatonline.github.com#36]
https://github.com/TheDigitalCatOnline/thedigitalcatonline.github.com/blob/2d09d376b604a6362013d85cd8677bd35e15a68b/blog/2020/03/27/mixin-classes-in-python/index.html#L881

Mistakes in header https://www.thedigitalcatonline.com/blog/2020/03/27/mixin-classes-in-python/#using-mixins-to-hijack-inheritance

### Mistake:

> <p>then the <code>__init__</code> method would first be provided by <code>Button</code>, and its <code>super</code> would call the <code>__init__</code> method of <code>SingleDimensionMixin</code>. 
It should be is:
> <p>then the <code>__init__</code> method would first be provided by <code>Button</code>, and its <code>super</code> would call the <code>__init__</code> method of <code>GraphicalEntity</code>. 
For class Button super() is GraphicalEntity.

### Mistake too:
> This would however result in an error, as the call <code>super().__init__(pos_x, pos_y, size_x, size_y)</code> in <code>Button</code> doesn't match the signature <code>def __init__(self, pos_x, pos_y, size):</code> of <code>SingleDimensionMixin</code>.</p>

The error occurs because `Square Button(10, 20, 200)` passes three arguments, but `__init__` of the Button class expects four.

**Comment by lgiordani** [comment]
Thanks @akocur I will have a look as soon as possible :top:

**Comment by lgiordani** [comment]
@akocur Apologies for the delay, I just fixed the post, thank a lot for noticing the mistake and for taking the time to file the issue! Merry Christmas!

**Comment by akocur** [comment]
Thank you so much for the articles. They helped me to understand complex topics.
Merry Christmas!
