### ISSUE TITLE
test_binary.py inside binary.zip: 2x test_binary_or()

### ISSUE THREAD

**Issue by rioj7** [TheDigitalCatOnline/thedigitalcatonline.github.com#41]
The file `test_binary.py` inside `https://www.thedigitalcatonline.com/code/python-oop-tdd-part2/binary.zip` is not identical to `https://www.thedigitalcatonline.com/code/python-oop-tdd-part1/test_binary_ver4.py`. And so is `code/python-oop-tdd-part2/test_binary.py`.

The function `test_binary_or()` is defined twice and `test_binary_xor()` is missing.

Also the whitespace is different and the comment lines (`#` compared to `##`)

**Comment by lgiordani** [comment]
Thanks, I set out to rewrite those posts and will get rid of the files, they are hard to maintain in sync. When the new version is online I will close this issue.

**Comment by lgiordani** [comment]
Hi! The new posts are available at https://www.thedigitalcatonline.com/blog/2015/05/13/python-oop-tdd-example-part1/ and this time there is a GitHub repository that hosts the code. Thanks a lot for your help!
