### ISSUE TITLE
Simple typo

### ISSUE THREAD

**Issue by superbeckgit** [TheDigitalCatOnline/thedigitalcatonline.github.com#5]
Loved the article on Refactoring with Tests in Python. I've followed similar procedures when refactoring code and I never feel comfortable if I don't add tests along the way.

But I found a typo near the end of the article.
"Speaking of tests, removing method will make"

I think you meant "methods".

**Comment by lgiordani** [comment]
Thank you, I fixed it. Thanks a lot for reading the post
