### ISSUE TITLE
typo RESPONDSE -> RESPONSE

### ISSUE THREAD

**Issue by slackorama** [TheDigitalCatOnline/thedigitalcatonline.github.com#8]
There's a typo on this line:

https://github.com/TheDigitalCatOnline/thedigitalcatonline.github.com/blob/87e6bac9c3d3e59d37b91c7594479d8026f84fb1/blog/2016/11/14/clean-architectures-in-python-a-step-by-step-example/index.html#L1406

**Comment by lgiordani** [comment]
Fixed! Thank you very much :wink:
